# Generated by Django 4.0.6 on 2022-07-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpletodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
