# Generated by Django 4.0.6 on 2022-07-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpletodo', '0002_todo_update_date_alter_todo_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='insert_date',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
    ]
